### ISSUE TITLE
Form Validation for Sign Up Form

### ISSUE THREAD

**Issue by NazWright** [NazWright/my-example-repo#25]
# Background

- Currently, the sign up form does not have the same css layout as the sign in form. This was not added to the xd wireframe flow, and will need to be created after MVP.

# Issue Details

## Use Case(s): 
 
- As a user, when I enter invalid inputs, into any forms in the authentication process, i would like to see an indicator of an error, so that I can provide a valid input.  

## Acceptance Criteria: 

- The Sign Up Form and Login Form and Verification components successfully validate all form inputs

## Tasks

- [ ]  Add frontend validation to firstName input, no numbers or special characters
- [ ]  Add frontend validation to lastName input, no numbers or special characters
- [ ]  Add frontend validation to of input type email
- [ ]  Add phone validation type to phone input
- [ ]  Show error message on all validations
- [ ]  Ensure password input is protected. 
- [ ]  Add a confirm password input and ensure the value is the same in the password field
- [ ]  Disable SIgn Up Button Until All fields are input
- [ ] Catch any exceptions returned by Amazon Cognito 
 

notes: 
- Can we programmatically run the functionality that gets ran when you specify an input type? Can we leverage the native DOM validation in Javascript?
