### ISSUE TITLE
Form Validation of Log In Form

### ISSUE THREAD

**Issue by NazWright** [NazWright/my-example-repo#26]
# Issue Details

## Use Case(s): 
 
- As a user, when I enter invalid inputs, into any forms in the authentication process, i would like to see an indicator of an error, so that I can provide a valid input.  

## Acceptance Criteria: 

- Login Form validates both email and password form fields

## Tasks

- [ ]  Add frontend validation to of input type email
- [ ]  Add phone validation type to phone input
- [ ]  Show error message on all validations
- [ ]  Ensure password input is protected. 
- [ ]  Disable Login Button Until All fields are input
- [ ] Catch any exceptions returned by Amazon Cognito 
 

notes: 
- Can we programmatically run the functionality that gets ran when you specify an input type? Can we leverage the native DOM validation in Javascript?
