### ISSUE TITLE
Verification Code Form Validation

### ISSUE THREAD

**Issue by NazWright** [NazWright/my-example-repo#27]
# Background

- Currently, the sign up form does not have the same css layout as the sign in form. This was not added to the xd wireframe flow, and will need to be created after MVP.

# Issue Details

## Use Case(s): 
 
- As a user, when I enter invalid inputs, into any forms in the authentication process, i would like to see an indicator of an error, so that I can provide a valid input.  

## Acceptance Criteria: 

- The Verification components cansuccessfully validate the verificcation code number

## Tasks

- [ ]  Verification code input should be a number, no alphabetical or special characters
- [ ]  Show error message on all validations
- [ ]  Disable Verify Button
- [ ]  Change Button text to "Verify"
- [ ]  Ensure that all verification codes will have an expiration time
- [ ]  The verification code component should check to see if the verification code has not already expired.
- [ ]  If the verification code entered by the user is incorrect, amazon cognito will throw an exception when we try to confirmSignUp. We need to catch this exceptions and then display a message under the verification code input if this happens. 

notes: 
- Can we programmatically run the functionality that gets ran when you specify an input type? Can we leverage the native DOM validation in Javascript?
